-- MySQL Script generated by MySQL Workbench
-- Wed Apr 17 16:57:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema user-registrationn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema user-registration
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user-registration` DEFAULT CHARACTER SET utf8 ;
USE `user-registration` ;

-- -----------------------------------------------------
-- Table `user-registration`.`ListaPomieszczen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user-registration`.`ListaPomieszczen` (
  `id` INT NOT NULL,
  `name` VARCHAR(90) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user-registration`.`Gniazdka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user-registration`.`Gniazdka` (
  `id` INT NOT NULL,
  `name` VARCHAR(90) NULL,
  `description` VARCHAR(90) NULL,
  `properties` VARCHAR(90) NULL,
  `state` TINYINT NULL,
  `ListaPomieszczen_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Gniazdka_ListaPomieszczen_idx` (`ListaPomieszczen_id` ASC),
  CONSTRAINT `fk_Gniazdka_ListaPomieszczen`
    FOREIGN KEY (`ListaPomieszczen_id`)
    REFERENCES `user-registration`.`ListaPomieszczen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user-registration`.`tbl_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user-registration`.`tbl_member` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(200) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `role` ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  `apartment_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `user-registration`.`HistoriaUzytkowania`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user-registration`.`HistoriaUzytkowania` (
  `id` INT NOT NULL,
  `id_user` INT NOT NULL,
  `name` VARCHAR(90) NULL,
  `Gniazdka_id` INT NOT NULL,
  `Data` DATETIME NULL,
  `tbl_member_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_HistoriaUzytkowania_Gniazdka1_idx` (`Gniazdka_id` ASC),
  INDEX `fk_HistoriaUzytkowania_tbl_member1_idx` (`tbl_member_id` ASC),
  CONSTRAINT `fk_HistoriaUzytkowania_Gniazdka1`
    FOREIGN KEY (`Gniazdka_id`)
    REFERENCES `user-registration`.`Gniazdka` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HistoriaUzytkowania_tbl_member1`
    FOREIGN KEY (`tbl_member_id`)
    REFERENCES `user-registration`.`tbl_member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
